export const palabras = [
  {
    id: 1,
    palabra: "me",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 2,
    palabra: "JavaScript",
    lenguajeProgramacion: true,
    usos: 1,
  },
  {
    id: 3,
    palabra: "el",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 4,
    palabra: "la",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 5,
    palabra: "gusta",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 6,
    palabra: "odio",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 7,
    palabra: "no",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 8,
    palabra: "muy",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 9,
    palabra: "y",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 10,
    palabra: "Java",
    lenguajeProgramacion: true,
    usos: 1,
  },
  {
    id: 11,
    palabra: "mucho",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 12,
    palabra: "de",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 13,
    palabra: "poco",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 14,
    palabra: "programador",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 15,
    palabra: "amigo",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 16,
    palabra: "programadora",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 17,
    palabra: "amiga",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 18,
    palabra: "soy",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 19,
    palabra: "tambien",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 20,
    palabra: "pero",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 21,
    palabra: "gustan",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 22,
    palabra: "gatos",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 23,
    palabra: "los",
    lenguajeProgramacion: false,
    usos: 1,
  },
  {
    id: 24,
    palabra: "perros",
    lenguajeProgramacion: false,
    usos: 1,
  },
];
